#!/bin/bash
# Quick Fix Script for Game Client

echo "📋 Game Client Debugging Guide"
echo "=============================="
echo ""
echo "✅ VERIFIED:"
echo "  - API Client exists: /dist/js/api.js"
echo "  - Base URL correct: http://localhost:8080/api/v1"
echo "  - Shop items seeded: 25 items including egg accelerators"
echo ""
echo "❌ ISSUE FOUND:"
echo "  - game.html uses 'apiClient' but NEVER imports it"
echo "  - JavaScript error: 'apiClient is not defined'"
echo ""
echo "🔧 SOLUTION:"
echo ""
echo "Add this at the TOP of the <script> section in game.html:"
echo ""
echo "  <script type=\"module\">"
echo "    import { apiClient } from './dist/js/api.js';"
echo "    window.apiClient = apiClient;  // Make it global"
echo ""
echo "OR convert the entire script to module type and import there."
echo ""
echo "🚀 MANUAL FIX STEPS:"
echo "1. Open game-client/game.html"
echo "2. Find line ~1050-1080 (where <script> starts)"
echo "3. Add: import { apiClient } from './dist/js/api.js';"
echo "4. Refresh browser"
echo ""
echo "💡 ALTERNATIVE: Check browser console (F12) for actual errors"
